### ISSUE TITLE
Is it possible to make closing bracket on a new line if new line is entered?

### ISSUE THREAD

**Issue by jodusan** [itmammoth/doorboy.vim#54]
When you have the following situation:

|
(
you get (|)
< enter >
resulting :
(
|)

Can you turn on the "newline jump" when you press enter, so that the closing bracket is on a newline?

|
(
(|)
< enter >
(
|
)

**Comment by itmammoth** [comment]
It sounds good.
I'll take it 👍 
Thanks.

**Comment by itmammoth** [comment]
@dulex123 If you go with [vim-endwise](https://github.com/tpope/vim-endwise) or other plugins taking \<CR> mapping, please have a look at the https://github.com/itmammoth/doorboy.vim/blob/master/README.md#notice
